export const SITE = {
  website: "https://timoelsesser.com/",
  author: "Timo Elsesser",
  profile: "https://timoelsesser.com/",
  desc: "Personal site of Timo Elsesser — AI Enthusiast. Projects, notes and contacts.",
  title: "Timo Elsesser",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Moscow",
} as const;
